### ISSUE TITLE
how to run the code?

### ISSUE THREAD

**Issue by muzi-8** [shaohua0116/Activation-Visualization-Histogram#2]
I have read your code and try to run the code，but it failed。
firstly 
the module “tfplot” I can‘t installed
secondly
there is no “datasets.mnist” module
so how can I do ? how to fix it?
thanks

**Comment by shaohua0116** [comment]
Can you provide the error information as well as which commit did you clone?

**Comment by shaohua0116** [comment]
Could you provide me with the further information of this issue?
