### ISSUE TITLE
Error Downloading Datasets

### ISSUE THREAD

**Issue by Witty-Kitty** [shaohua0116/Activation-Visualization-Histogram#4]
I run this command as instructed:

`python download.py --dataset MNIST SVHN CIFAR10`

It seems to download things and then exits with an error message asking me to : 

`ValueError: Please at least specify one dataset to be downloaded.`

Then when I try to run the script, it says the data has not been downloaded.

**Comment by shaohua0116** [comment]
The datasets should be downloaded by executing the command you mentioned. Could you check the directory **datasets/**? Subfolders should contain both files named **data.hy** and **id.txt**.

**Comment by Witty-Kitty** [comment]
The datasets directory has the following...
**Directories**
cifar10
mnist
svhn

**Files:**
cifar10.py
__init__.py
__init__.pyc
mnist.py
mnist.pyc
svhn.py

That's it.
The directories make me think that the data has infact been downloaded but when I try run 
`python script.py`
I get this
`IOError: Dataset not found. Please make sure the dataset was downloaded.`

It is looking for mnist data and not finding it.

**Comment by Witty-Kitty** [comment]
This is the entire stack trace from attempting to download the mnist data:

`python download.py --dataset MNIST

Downloading  train-images-idx3-ubyte.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9680k  100 9680k    0     0   583k      0  0:00:16  0:00:16 --:--:--  660k
Unzip  train-images-idx3-ubyte.gz

Downloading  train-labels-idx1-ubyte.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28881  100 28881    0     0  30671      0 --:--:-- --:--:-- --:--:-- 30659
Unzip  train-labels-idx1-ubyte.gz
gzip: ./datasets/mnist/train-labels-idx1-ubyte already exists; do you wish to overwrite (y or n)? y

Downloading  t10k-images-idx3-ubyte.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1610k  100 1610k    0     0   415k      0  0:00:03  0:00:03 --:--:--  415k
Unzip  t10k-images-idx3-ubyte.gz
gzip: ./datasets/mnist/t10k-images-idx3-ubyte already exists; do you wish to overwrite (y or n)? y

Downloading  t10k-labels-idx1-ubyte.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4542  100  4542    0     0   7722      0 --:--:-- --:--:-- --:--:--  7711
Unzip  t10k-labels-idx1-ubyte.gz
gzip: ./datasets/mnist/t10k-labels-idx1-ubyte already exists; do you wish to overwrite (y or n)? y

Preprocessing data...

Traceback (most recent call last):

  File "download.py", line 200, in <module>

    raise ValueError('Please at least specify one dataset to be downloaded.')

ValueError: Please at least specify one dataset to be downloaded.
`

**Comment by shaohua0116** [comment]
Please check if there are data.hy and id.txt under the directory ./datasets/mnist

**Comment by Witty-Kitty** [comment]
Within the mnist folder there's:

- t10k-images-idx3-ubyte

- t10k-labels-idx1-ubyte

- train-images-idx3-ubyte

- train-labels-idx1-ubyte

**Comment by shaohua0116** [comment]
Looks like the dataset is not well preprocessed. I would suggest you remove the directory `./dataets/mnist` and try to download and preprocess MNIST dataset again with `download.py` . Also, please make sure the library progressbar is installed.

**Comment by Witty-Kitty** [comment]
Hey.
So I discovered a small typo was at the root of all my troubles.
In 'download.py', you set the flag for adding arguments to be` --datasets `then in the documentation you give the command for downloading data with the flag as `--dataset`.

Adding the 's' made everything run as expected.
