### ISSUE TITLE
May I ask what conclusion can draw from this experiment?

### ISSUE THREAD

**Issue by l11x0m7** [shaohua0116/Activation-Visualization-Histogram#5]
Hi, I've seen your READM.md and your model codes. And it's really awesome works. However, I don't really understand what this pics shown in your experiment. If you could add your conclusion, it will be great and I'll really appreciate it!

**Comment by shaohua0116** [comment]
Sorry for the delayed response.

As I stated in the README, ideally, desire activations of every layer are close to *zero mean* and *unit variance* to make tensors propagated through several layers converge towards zero mean and unit variance. The learning can, therefore, be stabilized by preventing gradients from being vanishing and exploding.

Aiming to present clear at a glance comparisons among different activations, this implementation only focuses on visualizing and histogramming activations on Tensorboard. Therefore, there is no quantitative comparison among them. For the detailed experiments, please refer to the original [paper](https://arxiv.org/abs/1706.02515) and this informative thread on [Reddit](https://www.reddit.com/r/MachineLearning/comments/6g5tg1/r_selfnormalizing_neural_networks_improved_elu/)

**Comment by l11x0m7** [comment]
Thanks.
